with open("docs/PLAN.md", "r") as f:
    text = f.read()

text = text.replace(
    '  (generated by `scripts/generate_notebook_05.py`) implements the design below. No ML has been\n124	executed on the laptop; the notebook runs on Colab/Kaggle and exports to `temporal_inductive/`. Results\n125	in `docs/TEMPORAL_INDUCTIVE_EVALUATION.md` remain PENDING until then.*',
    '  (generated by `scripts/generate_notebook_05.py`) implements the design below. Results from the Tesla T4 execution have been exported to `results/temporal_inductive/` and documented in `docs/TEMPORAL_INDUCTIVE_EVALUATION.md`.*'
)

# Replace the checkboxes
import re

text = re.sub(
    r'\* \[ \] Evaluate the frozen XGBoost / GraphSAGE / RGCN models per step for 35-49 \(`per_step_metrics\.csv`\)\n129	\* \[ \] Measure label-free graph, address, and feature drift per step \(`drift_metrics\.csv`\)\n130	\* \[ \] Compare static \(1-34\) vs expanding \(1\.\.t-1\) RGCN retraining \(`static_vs_expanding\.csv`\)\n131	\* \[ \] Test one pre-registered rolling window, W=20 \(`rolling_window\.csv`\)\n132	\* \[ \] Break RGCN performance down by seen/unseen address context \(`inductive_metrics\.csv`\)\n133	\* \[ \] Recompute historical `T->A->T` availability under the prediction-time rule \(`historical_path_metrics\.csv`\)\n134	\* \[ \] Compare frozen vs adaptive thresholds, keeping PR-AUC \(threshold-free\) primary \(`threshold_analysis\.csv`\)\n135	\* \[ \] Execute on Colab/Kaggle and populate the results sections from the artifacts',
    r'* [x] Evaluate the frozen XGBoost / GraphSAGE / RGCN models per step for 35-49 (`per_step_metrics.csv`)\n129	* [x] Measure label-free graph, address, and feature drift per step (`drift_metrics.csv`)\n130	* [x] Compare static (1-34) vs expanding (1..t-1) RGCN retraining (`static_vs_expanding.csv`)\n131	* [x] Test one pre-registered rolling window, W=20 (`rolling_window.csv`)\n132	* [x] Break RGCN performance down by seen/unseen address context (`inductive_metrics.csv`)\n133	* [x] Recompute historical `T->A->T` availability under the prediction-time rule (`historical_path_metrics.csv`)\n134	* [x] Compare frozen vs adaptive thresholds, keeping PR-AUC (threshold-free) primary (`threshold_analysis.csv`)\n135	* [x] Execute on Colab/Kaggle and populate the results sections from the artifacts',
    text
)
with open("docs/PLAN.md", "w") as f:
    f.write(text)
